server:
  port: 8764

spring:
  application:
    name: hystrix-service-lucy

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"